services:
  shoppinglist:
    image: shubhamgoel23/shoppinglist:h2
    hostname: shoppinglist
    deploy:
      replicas: 1
    expose:
      - 8080
    restart: unless-stopped
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shoppinglist
    ports:
      - 80:8080