services:
  shoppinglist:
    image: shubhamgoel23/shoppinglist:postgres
    deploy:
      replicas: 1
    environment:
      DB_URL: jdbc:postgresql://database/shoppinglist
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DDL_AUTO: update
    restart: unless-stopped
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: shoppinglist
      PGDATA: /data
    volumes:
      - ./db-data/:/data
    restart: unless-stopped
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
#  cloudbeaver:
#    image: dbeaver/cloudbeaver
#    restart: unless-stopped
#    ports:
#      - 8081:8978
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shoppinglist
    ports:
      - 8080:8080
    restart: unless-stopped