logging:
  level:
    root: info
    web: info
    sql: trace
    feign: info
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.HikariConfig: DEBUG
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${app.default.timezone}

spring:
  profiles:    active:    - dev
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jpa:
    open-in-view: false    show-sql: false    properties:      hibernate:
        generate_statistics: false
        format_sql: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 20
        jdbc:
          batch_size: 500
          time_zone: ${app.default.timezone}
        order:
          inserts : true
          updates : true
        connection.provider_disables_autocommit: true
      
  application:
    name: shoppinglist
  jackson: #these properties are overriden incase we configure @EnableWebMvc,in that case we need to implement custom MappingJackson2HttpMessageConverter
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    deserialization: 
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
        datasource:    hikari:      auto-commit: false
        h2:
    console:      enabled: true
    
      
server:
  shutdown: graceful
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true

app:
  default:
#    timezone: IST
    timezone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true
    
---
spring:
  config:
    activate:
      on-profile:
      - dev
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:    hibernate:
      ddl-auto: none  datasource:   url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
   driver-class-name: org.h2.Driver
   username: sa
   password: password
  h2:    console:      settings:        web-allow-others: true
---
spring:  config:    activate:      on-profile:      - test
  flyway:
    enabled: false
    baseline-on-migrate: true
    
  jpa:
    hibernate:
      ddl-auto: create-drop  datasource:    url: jdbc:tc:mysql:latest:///testdb
