logging:
  level:
    root: info
    web: trace
    sql: debug
    feign: info
    com.zaxxer.hikari: info
    com.zaxxer.hikari.HikariConfig: info
    org:
      hibernate:
        type: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${app.default.timezone}
spring:
  profiles:
    active:
  #      - postgres_live
  #      - liquibase
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: ${DB_URL:jdbc}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    hikari:
      auto-commit: false
      minimum-idle: 0
      maximum-pool-size: 100
      max-lifetime: 900000
  h2:
    console:
      enabled: @h2.enable@
      settings:
        web-allow-others: @h2.enable@
  flyway:
    enabled: false
  liquibase:
    enabled: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      javax.persistence.query.timeout: 60000 #ms
      hibernate:
        generate_statistics: false
        format_sql: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 20
        jdbc:
          batch_size: ${app.datasource.batch_size}
          time_zone: ${app.default.timezone}
          batch_versioned_data: true
        order:
          inserts: true
          updates: true
        connection.provider_disables_autocommit: true
        id.optimizer.pooled.preferred: pooled-lo
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
  application:
    name: shoppinglist
  jackson: #these properties are overridden in case we configure @EnableWebMvc,in that case we need to implement custom MappingJackson2HttpMessageConverter
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    deserialization:
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  web:
    resources:
      add-mappings: false
  transaction:
    default-timeout: 60
server:
  shutdown: graceful
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB
  use-forward-headers: true
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true

app:
  default:
    #    timezone: IST
    timezone: UTC
  datasource:
    batch_size: 500

springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true
---
spring:
  config:
    activate:
      on-profile:
        - liquibase
  flyway:
    enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    parameters:
      sequenceBatch: ${app.datasource.batch_size}
---
spring:
  profiles:
    group:
      test:
        - @profile.db.test@
        - liquibase
---
spring:
  config:
    activate:
      on-profile:
        - mysql
  datasource:
    url: jdbc:tc:mysql:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - mssql
  datasource:
    url: jdbc:tc:sqlserver:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - postgres
  datasource:
    url: jdbc:tc:postgresql:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - oracle
  datasource:
    url: jdbc:tc:oracle:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - mariadb
  datasource:
    url: jdbc:tc:mariadb:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - cockroachdb
  datasource:
    url: jdbc:tc:cockroach:latest:///testdb
---
spring:
  config:
    activate:
      on-profile:
        - db2
  datasource:
    url: jdbc:tc:db2:latest:///testdb
---