logging:
  level:
    root: info
    web: info
    sql: debug
    feign: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,${app.default.timezone}

spring:
  flyway:
    enabled: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jpa:
    open-in-view: false
        show-sql: false
        hibernate:
          ddl-auto: create-drop    properties:      hibernate.generate_statistics: true
      hibernate.format_sql: true
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 20
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts : true
      hibernate.order_updates : true
      
  application:
    name: shoppinglist
  jackson: #these properties are overriden incase we configure @EnableWebMvc,in that case we need to implement custom MappingJackson2HttpMessageConverter
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    deserialization: 
      fail-on-unknown-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
        datasource:    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
      h2:
    console:      enabled: true
    
      
server:
  shutdown: graceful
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true

app:
  default:
    timezone: IST

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  cache:
    disabled: true
